version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./_mongo:/data/db # persist data
  # go-server:
  #   build: .
  #   container_name: go-server
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     GO_ENV: production
  #     PORT: 8080
  #     MONGO_URL: mongodb://user:password@mongo:27017
  #   depends_on:
  #     - mongo